version: '3.4'
services:
  web:
    container_name: laravel_web
    build:
      context: ./
      dockerfile: php.docker
    ports:
      - "9090:80"
    links:
      - db
    volumes:
      - ./src/:/var/www
      - ./src/public:/var/www/html
    networks:
      laranet2:
        ipv4_address: 172.25.12.103
  db:
    container_name: laravel_mysql
    privileged: true
    restart: always
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: larauser
      MYSQL_PASSWORD: larapass
    ports:
      - 9091:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      laranet2:
        ipv4_address: 172.25.12.102
  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 9092:80
    environment:
      - PMA_ARBITRARY=1
networks:
    laranet2:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.25.12.0/24